---
openapi: 3.0.0
info:
  title: Big Data Model Training
  description: |-
    # Authentication

    <!-- ReDoc-Inject: <security-definitions> -->
  version:
servers:
- url: /open-api/bigdata/v2
security:
- Sign: []
tags:
- name: data-mining
  description: Data Mining Training Phase
paths:
  /models:
    get:
      tags:
      - data-mining
      summary: Paginated query for model list
      operationId: dataMiningGetModels
      parameters:
      - name: name
        in: query
        description: Query models by name (fuzzy search)
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: model-1
      - name: trainable
        in: query
        description: "Whether the model is trainable (0 - not trainable, 1 - trainable)"
        required: false
        style: form
        explode: true
        schema:
          type: integer
        example: 1
      - name: pageNo
        in: query
        description: Page number
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: 1
      - name: pageSize
        in: query
        description: Number of items per page
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: 20
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataMiningListModel'
        "400":
          description: General error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /models/{modelCode}/versions:
    get:
      tags:
      - data-mining
      summary: Model Version List
      operationId: dataMiningGetModelVersion
      parameters:
      - name: modelCode
        in: path
        description: Model code
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataMiningListModelVersion'
        "400":
          description: General error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /models/{modelCode}/trainings:
    post:
      tags:
      - data-mining
      summary: Model Training
      operationId: dataMiningModelTraining
      parameters:
      - name: modelCode
        in: path
        description: Model code
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: Xsdfsfd24dfsadfsaf
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/modelCode_trainings_body'
            encoding:
              file:
                contentType: application/octet-stream
                style: form
      responses:
        "201":
          description: Successful processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: General error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    DataMiningListModelVersion:
      type: object
      properties:
        list:
          type: array
          description: Array of model versions
          items:
            $ref: '#/components/schemas/DataMiningListModelVersion_list'
      description: "Model version during the training phase, JSON format object"
    DataMiningListModel:
      type: object
      properties:
        list:
          type: array
          description: Array of models
          items:
            $ref: '#/components/schemas/DataMiningListModel_list'
        pagination:
          $ref: '#/components/schemas/DataMiningListModel_pagination'
      description: "Data structure of the model list during the training phase, JSON format object"
    inline_response_400:
      properties:
        code:
          type: integer
          description: "Error code, e.g., 40000404"
          example: 40000404
        message:
          type: string
          description: "Error message, e.g., \"Data not found\", \"Failed to modify data\""
          example: Unknown error
    modelCode_trainings_body:
      required:
      - file
      type: object
      properties:
        file:
          type: string
          description: "Training data file, supports Excel 2007 and CSV (comma-separated)"
          format: binary
        source:
          type: string
          description: Training source
          example: dam
        sourceId:
          type: string
          description: Training source ID
          example: damuuiduuiduuid
        sourceName:
          type: string
          description: Training source name
          example: dam-trainin-a-model
    inline_response_201:
      type: object
      properties:
        id:
          type: string
          description: "Training record ID, used to query the training status"
          example: uuiduuiduuid
    DataMiningListModelVersion_list:
      type: object
      properties:
        id:
          type: string
          description: Model version ID
          example: uuiduuiduuid
        description:
          type: string
          description: Model version description
          example: Upgrade model accuracy to 99%
        modelCode:
          type: string
          description: Model code
          example: Xsdfsfd24dfsadfsaf
        version:
          type: string
          description: Model version
          example: v1.0
        createdTime:
          type: number
          description: Model creation time in UTC timestamp
          example: 15612344562000
    DataMiningListModel_list:
      type: object
      properties:
        id:
          type: string
          description: "Model ID, globally unique and unrelated to business"
          example: uuiduuiduuid
        name:
          type: string
          description: "Model name, globally unique"
          example: model-1
        description:
          type: string
          description: Model description
          example: Linear regression training model
        code:
          type: string
          description: "Model code, externally visible, uniquely identifiable by code and version for model invocation"
          example: Xsdfsfd24dfsadfsaf
        inParams:
          type: string
          description: "Model input parameters, can be serialized as a JsonArray string"
          example: "[{\"name\":\"a\",\"dataType\":\"Integer\",\"description\":\"a\"},{\"name\":\"y\",\"dataType\":\"String\",\"description\":\"y\"}]"
        outParams:
          type: string
          description: "Model output parameters, can be serialized as a JsonArray string"
          example: "[{\"name\":\"pre\",\"dataType\":\"Double\",\"description\":\"a\"}]"
        trainable:
          type: integer
          description: "Whether the model can be updated with training (0 - not trainable, 1 - trainable)"
          example: 0
        createdTime:
          type: number
          description: Model creation time in UTC timestamp
          example: 15612344562000
        updateTime:
          type: number
          description: Model update time in UTC timestamp
          example: 15612344562000
    DataMiningListModel_pagination:
      type: object
      properties:
        total:
          type: integer
          description: Total number of models
          example: 100
        pageSize:
          type: integer
          description: Number of items per page
          example: 20
        current:
          type: integer
          description: Current page number
          example: 1
      description: Pagination object
  responses:
    GeneralError:
      description: General error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_400'
  securitySchemes:
    Sign:
      type: apiKey
      name: Authorization
      in: header
